export const routes = [
  {
    label: "A1",
    points: 2100,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A2",
    points: 2200,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A3",
    points: 2300,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A4",
    points: 2400,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A5",
    points: 2500,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A6",
    points: 2600,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A7",
    points: 2700,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A8",
    points: 2800,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A9",
    points: 2900,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "A10",
    points: 3000,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O1",
    points: 3100,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O2",
    points: 3200,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O3",
    points: 3300,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O4",
    points: 3400,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O5",
    points: 3500,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O6",
    points: 3600,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O7",
    points: 3700,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O8",
    points: 3800,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O9",
    points: 3900,
    completed: false,
    title: "Advanced 1",
  },
  {
    label: "O10",
    points: 4000,
    completed: false,
    title: "Advanced 1",
  },
]
